# Generated by Django 5.1.4 on 2025-04-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_icon',
            field=models.CharField(default='note', max_length=24),
        ),
    ]
